services:
  app:
    image: node:16.14.2
    container_name: green-rewards-api
    user: 'root'
    restart: always
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    command: bash -c "npm run start:dev"
    networks:
      - green_reward
  db:
    container_name: green-rewards-database
    image: postgres:16
    restart: always
    shm_size: 1g
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: green-rewards
    networks:
      - green_reward

networks:
  green_reward:
    name: green_reward
    driver: bridge
